### ISSUE TITLE
one frame pos position

### ISSUE THREAD

**Issue by AndroidUnityGit** [keel-210/OpenPose-Rig#6]
hello, How do you get the one frame pose estimation result ? I use openpose and 3d-post-baseline to get 3d-data.json, which is totally different from the JSON format provided by you. Are there any other steps in the middle,
my json: {"0": {"0": {"translate": [-526.1015, 0.0, 607.4599038791717]}, "1": {"translate": [-606.7712571744592, 29.97365833193502, 638.2196033433054]},

**Comment by keel-210** [comment]
This repository supports the posture information format output by tf-openpose as of February 27, 2018. If you want to use another format, rewrite the code.
